[versions]
agp = "8.10.1"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.29"
coreKtx = "1.17.0"
lifecycle = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.08.00"
room = "2.7.2"
serialization = "1.7.3"
ktor = "2.3.12"
appcompat = "1.7.1"
navigation = "2.9.3"
paging = "3.3.6"
constraintLayout = "1.1.1"
jReleases = "1.19.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging" }
compose-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout" }
roomRuntime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
roomKtx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
roomPaging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
roomCompiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
kotlinSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }

# Ktor
ktorServerCore = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktorServerNetty = { group = "io.ktor", name = "ktor-server-netty-jvm", version.ref = "ktor" }
ktorServerContentNegotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktorClientCore = { group = "io.ktor", name = "ktor-client-core-jvm", version.ref = "ktor" }
ktorClientCio = { group = "io.ktor", name = "ktor-client-cio-jvm", version.ref = "ktor" }
ktorClientContentNegotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktorSerializationJson = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinSerialization = { id = "plugin.serialization", version.ref = "kotlin" }
jReleaser = {id = "org.jreleaser", version.ref = "jReleases" }